name: Elytra
author: Ad5001
version: 2.1
api:
 - 3.0.0
 - 3.0.0-ALPHA7
main: Ad5001\Elytra\Main
load: STARTUP
commands: 
    opelytra:
        description: "Make your elytras your wear MAGIC !"
        usage: "/opelytra"
        permission: elytra.getopelytra
    boost:
        description: "Boost yourself in elytra !"
        usage: "/boost [strength = 2]"
        permission: elytra.boost
        aliases: [b]
permissions: 
    elytra.getopelytra:
        default: op
    elytra.boost:
        default: true